
services:
  sistemahotel:
    image: sistemahotel
    build:
      context: .
      dockerfile: SistemaHotel/Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - AppDbHost=application_db
      - AppDb=app
      - AppDbUser=${application_db_user}
      - AppDbPass=${application_db_pass}
      - AuthDbHost=authentication_db
      - AuthDb=auth
      - AuthDbUser=${authentication_db_user}
      - AuthDbPass=${authentication_db_pass}
      - EmailHost=${EmailHost}
      - EmailPort=${EmailPort}
      - EmailSsl=${EmailSsl}
      - EmailUser=${EmailUser}
      - EmailPass=${EmailPass}
      - AdminEmail=${AdminEmail}
    depends_on:
      - authentication_db
      - application_db
  authentication_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: ${authentication_db_user}
      POSTGRES_PASSWORD: ${authentication_db_pass}
    ports:
      - 15432:5432
    volumes:
      - authentication_data:/var/lib/postgresql/data
  application_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: ${application_db_user}
      POSTGRES_PASSWORD: ${application_db_pass}
    ports:
      - 25432:5432
    volumes:
      - application_data:/var/lib/postgresql/data
      - ./db/Schema.sql:/docker-entrypoint-initdb.d/10_Schema.sql

volumes:
  authentication_data:
  application_data: